spring.application.name=backend-api
server.port=8084

# Credenciales definidas previamente en el docker-compose
spring.datasource.url=jdbc:mysql://mysql_servidor_favoritos:3309/db_amazorg_favoritos?useSSL=false&serverTimezone=UTC
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate para crear tablas automáticamente en base al código
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
